### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by MikhailY** [Shevchik/WorldGuardExtender#13]
latest wgextender

[15:25:20] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to WGExtender v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[craftbukkit.jar:git-Paper-1474]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) [craftbukkit.jar:git-Paper-1474]
	at com.SirBlobman.combatlogx.utility.Util.call(Util.java:221) [CombatLogX.jar:?]
	at com.SirBlobman.combatlogx.Combat.punish(Combat.java:170) [CombatLogX.jar:?]
	at com.SirBlobman.combatlogx.listener.FinalMonitor.pue(FinalMonitor.java:91) [CombatLogX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor593.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [craftbukkit.jar:git-Paper-1474]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) [craftbukkit.jar:git-Paper-1474]
	at com.SirBlobman.combatlogx.utility.Util.call(Util.java:221) [CombatLogX.jar:?]
	at com.SirBlobman.combatlogx.listener.ListenBukkit.quit(ListenBukkit.java:148) [CombatLogX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [craftbukkit.jar:git-Paper-1474]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) [craftbukkit.jar:git-Paper-1474]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1147) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:343) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [craftbukkit.jar:git-Paper-1474]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [craftbukkit.jar:git-Paper-1474]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException

**Comment by Shevchik** [comment]
Need a full log.

**Comment by MikhailY** [comment]
Я не могу скинуть лог, и плагин сильно грузит
http://prntscr.com/k1s608

**Comment by Shevchik** [comment]
0.91% per lick is literally zero load.

**Comment by MikhailY** [comment]
А с ошибкой, что делать? Есть какой то выход без лога?
