### ISSUE TITLE
Error WGExtender blocklimits

### ISSUE THREAD

**Issue by dexter132** [Shevchik/WorldGuardExtender#14]
Ошибка в консоли при создании привата при включенном blocklimits в конфиге.

```
[14:45:28 INFO]: Greeny issued server command: /rg claim 213
[14:45:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rg claim 213' in wgextender.features.claimcommand.WGRegionCommandWrapper(region)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at wgextender.features.claimcommand.BlockLimits.processClaimInfo(BlockLimits.java:57) ~[?:?]
	at wgextender.features.claimcommand.WGRegionCommandWrapper.execute(WGRegionCommandWrapper.java:67) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-417cfb3-4487c1f]
	... 14 more
```
Когда отключаю blocklimits все хорошо

**Comment by dexter132** [comment]
Плагин последней версии. Версия ядра 1.13. Wg 7

**Comment by Shevchik** [comment]
No supported vault permissions plugin is enabled.
