### ISSUE TITLE
Ошибка при создании региона 1.13.2 PaperSpigot WG7 last dev build #1914

### ISSUE THREAD

**Issue by DarkKingArthas** [Shevchik/WorldGuardExtender#20]
```
[00:34:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rg claim 13' in wgextender.features.claimcommand.WGRegionCommandWrapper(region)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$3333.000000007C100F60.run(Unknown Source) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[Paper-1.13.2-b624.jar:git-Paper-624]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.AbstractMethodError: com/sk89q/worldedit/extension/platform/Actor.print(Lcom/sk89q/worldedit/util/formatting/text/Component;)V
at com.sk89q.worldguard.commands.region.RegionPrintoutBuilder.send(RegionPrintoutBuilder.java:355) ~[?:?]
at com.sk89q.worldguard.commands.region.RegionCommands.flag(RegionCommands.java:641) ~[?:?]
at wgextender.features.claimcommand.AutoFlags.setFlag(AutoFlags.java:79) ~[?:?]
at wgextender.features.claimcommand.AutoFlags.setFlagsForRegion(AutoFlags.java:66) ~[?:?]
at wgextender.features.claimcommand.WGRegionCommandWrapper.execute(WGRegionCommandWrapper.java:79) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper-1.13.2-b624.jar:git-Paper-624]
... 15 more
```

**Comment by DarkKingArthas** [comment]
Ещё от себя немного добавлю, считывает кол-во блоков для групп правильно, если превысить допустимое, то пишет разрешенную и текущую, но если сменить группу (я использую LuckPerms), то после смены на группу где максимум блоков увеличен, все равно показывает старое кол-во разрешенных блоков от другой группы в которой находился до этого, перезагрузка конфига не помогает, только перезапуск сервера, ну, а если попытаться заприватить территорию по норме, то вот ошибка выше.
