### ISSUE TITLE
Error on claim region - Paper version git-Paper-225 (MC: 1.14.4)  [WorldGuard] Loading WorldGuard v7.0.1-SNAPSHOT;1984-2647740

### ISSUE THREAD

**Issue by valenvaio** [Shevchik/WorldGuardExtender#21]
[08:21:29] [Server thread/WARN]: com.sk89q.minecraft.util.commands.CommandException: The plugin that registered this flag is not currently installed
[08:21:29] [Server thread/WARN]:        at com.sk89q.worldguard.commands.region.RegionCommands.flag(RegionCommands.java:574)
[08:21:29] [Server thread/WARN]:        at wgextender.features.claimcommand.AutoFlags.setFlag(AutoFlags.java:80)
[08:21:29] [Server thread/WARN]:        at wgextender.features.claimcommand.AutoFlags.setFlagsForRegion(AutoFlags.java:67)
[08:21:29] [Server thread/WARN]:        at wgextender.features.claimcommand.WGRegionCommandWrapper.execute(WGRegionCommandWrapper.java:79)
[08:21:29] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[08:21:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088)
[08:21:29] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[08:21:29] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by valenvaio** [comment]
error in config. flag from deinstall plugin.
